# Generated by Django 6.0.2 on 2026-02-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_term', models.CharField(choices=[('Term-I', 'TERM-I'), ('Term-II', 'TERM-II')], max_length=10)),
                ('term_startdate', models.DateField()),
                ('term_enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('is_current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1st Year', 'FIRST YEAR'), ('2nd Year', 'SECOND YEAR'), ('3rd Year', 'THIRD YEAR'), ('4th Year', 'FOURTH YEAR')], max_length=20)),
                ('program', models.CharField(choices=[('BTech', 'BTECH'), ('MBATech', 'MBATECH')], max_length=20)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('CE', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('CSEDS', 'Computer Science Engineering (Data Science)')], max_length=10)),
                ('div', models.CharField(blank=True, choices=[('Div-A', 'DIV-A'), ('Div-B', 'DIV-B')], max_length=10)),
                ('semester', models.CharField(choices=[('Sem-I', 'Semester I'), ('Sem-II', 'Semester II'), ('Sem-III', 'Semester III'), ('Sem-IV', 'Semester IV'), ('Sem-V', 'Semester V'), ('Sem-VI', 'Semester VI'), ('Sem-VII', 'Semester VII'), ('Sem-VIII', 'Semester VIII')], max_length=10)),
                ('class_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
            ],
            options={
                'unique_together': {('program', 'branch', 'semester', 'div', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=5)),
                ('sap_id', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicclass')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('class_associated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.academicclass')),
                ('faculty_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to='core.faculty')),
            ],
            options={
                'unique_together': {('subject_code', 'class_associated')},
            },
        ),
    ]
