# Generated by Django 6.0.2 on 2026-02-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_term', models.CharField(choices=[('I', 'Term-I'), ('II', 'Term-II')])),
                ('term_startdate', models.DateField()),
                ('term_enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('is_current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1st Year', 'FIRST YEAR'), ('2nd Year', 'SECOND YEAR'), ('3rd Year', 'THIRD YEAR'), ('4th Year', 'FOURTH YEAR')])),
                ('program', models.CharField(choices=[('BTech', 'BTECH'), ('MBATech', 'MBATECH')])),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('CE', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('CSEDS', 'Computer Science Engineering (Data Science)')])),
                ('div', models.CharField(choices=[('Div-A', 'DIV-A'), ('Div-B', 'DIV-B')])),
                ('semester', models.CharField(choices=[('Sem-I', 'Semester I'), ('Sem-II', 'Semester II'), ('Sem-III', 'Semester III'), ('Sem-IV', 'Semester IV'), ('Sem-V', 'Semester V'), ('Sem-VI', 'Semester VI'), ('Sem-VII', 'Semester VII'), ('Sem-VIII', 'Semester VIII')])),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
            ],
        ),
    ]
