# Generated by Django 6.0.2 on 2026-02-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='div',
            field=models.CharField(choices=[('Div-A', 'DIV-A'), ('Div-B', 'DIV-B')], null=True),
        ),
    ]
