# Generated by Django 6.0.2 on 2026-02-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicclass',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academicclass',
            name='div',
            field=models.CharField(blank=True, choices=[('Div A', 'DIV-A'), ('Div B', 'DIV-B')], max_length=10),
        ),
        migrations.AlterField(
            model_name='academicclass',
            name='semester',
            field=models.CharField(choices=[('Sem I', 'Semester I'), ('Sem II', 'Semester II'), ('Sem III', 'Semester III'), ('Sem IV', 'Semester IV'), ('Sem V', 'Semester V'), ('Sem VI', 'Semester VI'), ('Sem VII', 'Semester VII'), ('Sem VIII', 'Semester VIII')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='academicclass',
            unique_together={('program', 'branch', 'semester', 'div')},
        ),
    ]
