# Generated by Django 6.0.2 on 2026-02-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_class_div'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='div',
            field=models.CharField(blank=True, choices=[('Div-A', 'DIV-A'), ('Div-B', 'DIV-B')]),
        ),
    ]
